### ISSUE TITLE
Smartwatch+ app crashes with Medusa enabled

### ISSUE THREAD

**Issue by Drewbydrew** [CPDigitalDarkroom/HideMeX-iOS-10#4]
Reproducible with no other tweaks loaded and only that setting enabled. It's a pretty niche issue, but it's there. I've sent you the crash log via CrashReporter.

**Comment by kgfromthemv** [comment]
I also was having this problem, with the App myDlink Lite. I think it has something to do with resolutions or whether or not the App is optimized for retina devices because myDlink Lite is the only app that was crashing with Medusa enabled and it isn't optimized for my screen resolution. I'm on i7 on 10.1.1.

**Comment by sireddiie** [comment]
I'm having the same issue with dj lobo app

**Comment by sireddiie** [comment]
Same with dj lobo app

**Comment by haerik** [comment]
Same problem here with the app Bongo (local bus tracker). It's also not updated for higher screen resolution (and probably never will be). I can send a crash log if you want it.

Hopefully it's fixed soon, but in the mean time I'll just disable Medusa.

**Comment by CPDigitalDarkroom** [comment]
I thought I did have _supportsApplicationType: hooked turns out I had a typo and had _supportsApplicationTyle: instead. This crash should be fixed as of v1.0.3 though it does also add blacklisting an app to disable Medusa completely for it.
